/**
 * Practical examples of integrating text file download into the Shogi game
 * These examples show real-world use cases specific to this application
 */

import { downloadTextFile } from '@/lib/utils';
import type { CellData } from '@/hooks/useGameState';

// ============================================================================
// Example 1: Export Game in SFEN Format
// ============================================================================
export function exportGameAsSFEN(boardState: CellData[][], moveHistory: string[]) {
  const sfenLines = [
    '# Shogi Game Export',
    `# Date: ${new Date().toLocaleString()}`,
    '# Format: SFEN',
    '',
    '# Initial Position',
    'startpos',
    '',
    '# Moves',
    moveHistory.join(' '),
    '',
    '# End of Game'
  ];

  const content = sfenLines.join('\n');
  const filename = `shogi-game-${Date.now()}.sfen`;
  
  downloadTextFile(content, filename);
}

// ============================================================================
// Example 2: Export Move History as Readable Text
// ============================================================================
export function exportMoveHistory(moves: Array<{
  moveNumber: number;
  player: 'black' | 'white';
  notation: string;
  timestamp: Date;
}>) {
  const header = `将棋 Move History
Generated: ${new Date().toLocaleString()}
Total Moves: ${moves.length}
${'='.repeat(50)}
`;

  const moveLines = moves.map(move => {
    const playerSymbol = move.player === 'black' ? '☗' : '☖';
    const time = move.timestamp.toLocaleTimeString();
    return `${move.moveNumber}. ${playerSymbol} ${move.notation} (${time})`;
  });

  const content = header + '\n' + moveLines.join('\n');
  downloadTextFile(content, 'move-history.txt');
}

// ============================================================================
// Example 3: Export Captured Pieces
// ============================================================================
export function exportCapturedPieces(captures: {
  black: string[];
  white: string[];
}) {
  const content = `Captured Pieces
${'='.repeat(50)}

Black's Captures (持ち駒):
${captures.black.length > 0 ? captures.black.join(', ') : 'None'}

White's Captures (持ち駒):
${captures.white.length > 0 ? captures.white.join(', ') : 'None'}

Total Captures: ${captures.black.length + captures.white.length}
`;

  downloadTextFile(content, 'captured-pieces.txt');
}

// ============================================================================
// Example 4: Export Complete Game Report
// ============================================================================
export function exportCompleteGameReport(gameData: {
  startTime: Date;
  endTime: Date;
  winner: 'black' | 'white' | 'draw';
  totalMoves: number;
  averageMoveTime: number;
  moveHistory: string[];
  captures: { black: string[]; white: string[] };
}) {
  const duration = gameData.endTime.getTime() - gameData.startTime.getTime();
  const durationMinutes = Math.floor(duration / 60000);
  const durationSeconds = Math.floor((duration % 60000) / 1000);

  const content = `
╔═══════════════════════════════════════════════════════════╗
║           将棋 GAME REPORT                                ║
╚═══════════════════════════════════════════════════════════╝

Game Information:
─────────────────────────────────────────────────────────────
Start Time:     ${gameData.startTime.toLocaleString()}
End Time:       ${gameData.endTime.toLocaleString()}
Duration:       ${durationMinutes}m ${durationSeconds}s
Winner:         ${gameData.winner === 'draw' ? 'Draw' : gameData.winner === 'black' ? '☗ Black (Sente)' : '☖ White (Gote)'}

Statistics:
─────────────────────────────────────────────────────────────
Total Moves:    ${gameData.totalMoves}
Avg Move Time:  ${gameData.averageMoveTime.toFixed(1)}s
Black Captures: ${gameData.captures.black.length} pieces
White Captures: ${gameData.captures.white.length} pieces

Move History:
─────────────────────────────────────────────────────────────
${gameData.moveHistory.map((move, i) => `${i + 1}. ${move}`).join('\n')}

Captured Pieces:
─────────────────────────────────────────────────────────────
☗ Black: ${gameData.captures.black.join(', ') || 'None'}
☖ White: ${gameData.captures.white.join(', ') || 'None'}

─────────────────────────────────────────────────────────────
Report generated by Shogi Companion
${new Date().toISOString()}
  `.trim();

  const timestamp = gameData.startTime.toISOString().slice(0, 10);
  downloadTextFile(content, `shogi-report-${timestamp}.txt`);
}

// ============================================================================
// Example 5: Quick Export Function (use in React components)
// ============================================================================
export function quickExportGame(
  moveHistory: string[],
  captures: { black: string[]; white: string[] }
) {
  const content = `Quick Game Export
Date: ${new Date().toLocaleString()}
Moves: ${moveHistory.length}
Black Captures: ${captures.black.length}
White Captures: ${captures.white.length}

Move History:
${moveHistory.map((move, i) => `${i + 1}. ${move}`).join('\n')}

Black Captures: ${captures.black.join(', ') || 'None'}
White Captures: ${captures.white.join(', ') || 'None'}
`;

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  downloadTextFile(content, `shogi-export-${timestamp}.txt`);
}

// ============================================================================
// Example 6: Auto-save Feature
// ============================================================================
export function setupAutoSave(
  getGameState: () => any,
  intervalMinutes: number = 5
) {
  const interval = setInterval(() => {
    try {
      const state = getGameState();
      const content = JSON.stringify(state, null, 2);
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
      
      downloadTextFile(content, `autosave-${timestamp}.txt`);
      console.log('Game auto-saved successfully');
    } catch (error) {
      console.error('Auto-save failed:', error);
    }
  }, intervalMinutes * 60 * 1000);

  // Return cleanup function
  return () => clearInterval(interval);
}

// ============================================================================
// Example 7: Export Game as PGN-style Notation
// ============================================================================
export function exportAsPGN(gameMetadata: {
  event?: string;
  site?: string;
  date: Date;
  round?: string;
  black: string;
  white: string;
  result: string;
  moves: string[];
}) {
  const content = `[Event "${gameMetadata.event || 'Casual Game'}"]
[Site "${gameMetadata.site || 'Shogi Companion'}"]
[Date "${gameMetadata.date.toISOString().slice(0, 10)}"]
[Round "${gameMetadata.round || '1'}"]
[Black "${gameMetadata.black}"]
[White "${gameMetadata.white}"]
[Result "${gameMetadata.result}"]

${gameMetadata.moves.join(' ')}
`;

  downloadTextFile(content, 'shogi-game.pgn');
}

