import { useState } from 'react';
import { Download, FileText } from 'lucide-react';
import { downloadTextFile } from '@/lib/utils';

/**
 * Demo component showcasing the text file download feature
 * This component generates dynamic text content and downloads it as a .txt file
 */
const TextFileDownloadDemo = () => {
  const [customText, setCustomText] = useState('');

  // Example 1: Download predefined content
  const handleDownloadSample = () => {
    const content = `Shogi Game Export
Generated: ${new Date().toLocaleString()}

This is a sample text file generated dynamically.
You can customize this content based on your needs.

Features:
- Client-side file generation
- No server storage required
- Instant download
- Lightweight implementation`;

    downloadTextFile(content, 'shogi-sample.txt');
  };

  // Example 2: Download user-entered content
  const handleDownloadCustom = () => {
    if (customText.trim()) {
      downloadTextFile(customText, `custom-${Date.now()}.txt`);
    }
  };

  // Example 3: Download game statistics (dynamic data)
  const handleDownloadStats = () => {
    const stats = {
      gameDate: new Date().toISOString(),
      duration: '15 minutes',
      moves: 42,
      winner: 'Player 1',
    };

    const content = `=== Shogi Game Statistics ===

Date: ${stats.gameDate}
Duration: ${stats.duration}
Total Moves: ${stats.moves}
Winner: ${stats.winner}

Generated by Shogi Companion
`;

    downloadTextFile(content, `game-stats-${Date.now()}.txt`);
  };

  return (
    <div className="p-6 max-w-2xl mx-auto space-y-6">
      <div className="bg-white rounded-lg shadow-md p-6">
        <div className="flex items-center gap-2 mb-4">
          <FileText className="w-6 h-6 text-amber-600" />
          <h2 className="text-2xl font-bold">Text File Download Demo</h2>
        </div>
        
        <p className="text-gray-600 mb-6">
          This demo showcases client-side text file generation and download.
          Files are created in memory and downloaded instantly without server storage.
        </p>

        {/* Example 1: Predefined content */}
        <div className="border border-gray-200 rounded-lg p-4 mb-4">
          <h3 className="font-semibold mb-2">Example 1: Download Sample Text</h3>
          <p className="text-sm text-gray-600 mb-3">
            Download a predefined sample file with game information
          </p>
          <button
            onClick={handleDownloadSample}
            className="bg-amber-600 hover:bg-amber-700 text-white font-medium py-2 px-4 rounded-lg transition-colors flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            Download Sample
          </button>
        </div>

        {/* Example 2: Custom content */}
        <div className="border border-gray-200 rounded-lg p-4 mb-4">
          <h3 className="font-semibold mb-2">Example 2: Download Custom Text</h3>
          <p className="text-sm text-gray-600 mb-3">
            Enter your own text and download it as a file
          </p>
          <textarea
            value={customText}
            onChange={(e) => setCustomText(e.target.value)}
            placeholder="Enter your custom text here..."
            className="w-full px-3 py-2 border border-gray-300 rounded-lg mb-3 min-h-[100px] focus:outline-none focus:ring-2 focus:ring-amber-500"
          />
          <button
            onClick={handleDownloadCustom}
            disabled={!customText.trim()}
            className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-4 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            Download Custom Text
          </button>
        </div>

        {/* Example 3: Dynamic data */}
        <div className="border border-gray-200 rounded-lg p-4">
          <h3 className="font-semibold mb-2">Example 3: Download Game Statistics</h3>
          <p className="text-sm text-gray-600 mb-3">
            Generate and download dynamic game statistics
          </p>
          <button
            onClick={handleDownloadStats}
            className="bg-green-600 hover:bg-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            Download Statistics
          </button>
        </div>
      </div>

      {/* Usage Code Example */}
      <div className="bg-gray-50 rounded-lg p-6">
        <h3 className="font-semibold mb-3">Usage in Your Code:</h3>
        <pre className="bg-gray-900 text-green-400 p-4 rounded-lg overflow-x-auto text-sm">
{`import { downloadTextFile } from '@/lib/utils';

// Simple usage
downloadTextFile('Hello World!', 'greeting.txt');

// With dynamic content
const content = \`Game: \${gameData.name}
Score: \${gameData.score}\`;
downloadTextFile(content, 'game-export.txt');

// On button click
<button onClick={() => downloadTextFile(data, 'export.txt')}>
  Download
</button>`}
        </pre>
      </div>
    </div>
  );
};

export default TextFileDownloadDemo;
